[build]
  base = "/"
  publish = "/public/"
  command = "npm i"

  # Directory with the serverless Lambda functions to deploy to AWS.
  functions = "./functions/"

[context.production]
  environment = { CLOCKIFY_APIKEY = "", CLOCKIFY_USER = "", CLOCKIFY_WORKSPACE = "" }
