name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
#    - name: npm install, build, and test
#      run: |
#        npm ci
#        npm run build --if-present
#        npm test
#      env:
#        CI: true
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v2.0.2
      with:
        # This will be used for authentication. You can find it in your heroku homepage account settings
        heroku_api_key: ${{ secrets.HEROKU_USER_AUTH }}
        # Email that you use with heroku
        heroku_email: ${{ secrets.HEROKU_USER_EMAIL }}
        # The appname to use for deploying/updating
        heroku_app_name: ba-registrations
        branch: master
